/* LLWS 2026 Office Pool leaderboard.
   Reads data.json (regenerated by pool/update.py). No dependencies, no build.

   URL options:  ?view=standings|teams   pin a single view
                 ?rotate=20              seconds per view (default 14)
                 ?safe=4                 overscan inset, percent
                 ?rows=8                 force rows per standings page
                 ?debug=1                overlay what this screen reports
   Keyboard:     Space pauses rotation, Left/Right switch views,
                 [ and ] fit the picture to the TV, 0 resets.

   COMPATIBILITY: the office TV is driven by a BrightSign player, whose
   firmware carries an older Chromium than a desktop browser. Nothing here
   uses optional chaining, nullish coalescing or flexbox gap - all of which
   are Chromium 80/84 features, and the first two of which would fail to
   parse and take the whole page down rather than degrade. Keep it that way. */

const params = new URLSearchParams(location.search);
const ROTATE_OVERRIDE = parseFloat(params.get('rotate'));
const REFRESH_MS = 60000;
const PINNED = params.get('view');
const ROWS_OVERRIDE = parseInt(params.get('rows'), 10) || 0;
const DEBUG = params.get('debug') === '1';

/* ------------------------------------------------------- surviving a reload
   A signage player reloads the page on its own schedule, and BrightAuthor's
   default is often shorter than one full rotation. Starting from view 0
   every time means the later screens are never reached: the room sees page
   one of the standings and nothing else, no matter how long the TV is on.

   So the last screen shown is remembered, and a fresh load picks up at the
   NEXT one. However often the player reloads, the whole rotation still gets
   seen. */
/* ------------------------------------------------------ running stale code
   A signage player can hold on to a cached app.js long after a deploy, which
   shows the room fresh scores rendered by old code - data.json is fetched
   with a unique ?t= every time, the script is not. The script can tell: it
   reads the version off its own tag and compares it with the version in
   data.json, which is always current. On a mismatch it reloads once through
   a URL the player has never seen, which pulls a fresh index.html and with it
   fresh script and stylesheet URLs.

   The guard is the URL itself rather than storage, so there is no way to get
   into a reload loop on a player where storage does not persist. */
const MY_BUILD = (function () {
  const tags = document.getElementsByTagName('script');
  for (let i = 0; i < tags.length; i++) {
    const m = /app\.js\?v=([A-Za-z0-9]+)/.exec(tags[i].src || '');
    if (m) return m[1];
  }
  return '';
})();

function reloadIfStale(data) {
  if (!data.build || !MY_BUILD || data.build === MY_BUILD) return false;
  if (params.get('cb') === data.build) return false;   // already tried this one
  const next = new URLSearchParams(location.search);
  next.set('cb', data.build);
  location.replace(location.pathname + '?' + next.toString());
  return true;
}

const VIEW_KEY = 'llws-view-index';
let resumeFrom = 0;
try {
  const stored = parseInt(localStorage.getItem(VIEW_KEY), 10);
  if (!isNaN(stored)) resumeFrom = stored + 1;
} catch (e) { /* storage disabled on this player; start at the top */ }
let seeded = false;

/* ----------------------------------------------------------------- overscan
   Televisions crop the edges of an HDMI signal, typically 2-5% a side, which
   is what made the score column disappear off the side of the office TV.
   Everything is inset by a safe area the operator can tune on the screen
   itself: [ and ] nudge it, 0 resets, and the value is remembered per screen
   so it survives a reload. ?safe=4 sets it directly where there is no
   keyboard. */
const SAFE_KEY = 'llws-safe-percent';
const clampSafe = v => Math.min(12, Math.max(0, v));

function readSafe() {
  const fromUrl = parseFloat(params.get('safe'));
  if (!Number.isNaN(fromUrl)) return clampSafe(fromUrl);
  let stored = NaN;
  try { stored = parseFloat(localStorage.getItem(SAFE_KEY)); } catch (e) {}
  return Number.isNaN(stored) ? 3 : clampSafe(stored);
}

let safePercent = readSafe();
let safeHudTimer = null;

function applySafe(show) {
  const root = document.documentElement;
  root.style.setProperty('--safe-x', safePercent + 'vw');
  // Vertical crop is usually a little less aggressive than horizontal.
  root.style.setProperty('--safe-y', (safePercent * 0.8) + 'vh');
  if (!show) return;
  const hud = $('#safe-hud'), stage = $('#stage');
  if (!hud) return;
  hud.innerHTML = 'Screen fit &nbsp;' + safePercent.toFixed(1) + '%' +
    '<small>[ and ] to adjust &middot; 0 to reset</small>';
  hud.classList.add('on');
  stage.classList.add('calibrating');
  clearTimeout(safeHudTimer);
  safeHudTimer = setTimeout(() => {
    hud.classList.remove('on');
    stage.classList.remove('calibrating');
  }, 2600);
}

function nudgeSafe(delta) {
  safePercent = clampSafe(Math.round((safePercent + delta) * 10) / 10);
  try { localStorage.setItem(SAFE_KEY, safePercent); } catch (e) {}
  applySafe(true);
  if (currentData) { rebuildViews(currentData); renderStandings(currentData); }
}

/* Dwell per view: big pools paginate into more views, so shorten each one to
   keep a full cycle around a minute rather than a minute and a half. */
function rotateMs() {
  if (ROTATE_OVERRIDE) return ROTATE_OVERRIDE * 1000;
  const per = Math.min(14, Math.max(8, 75 / Math.max(1, VIEWS.length)));
  return per * 1000;
}

/* Views are built at render time: the standings paginate so rows stay large
   enough to read across a room no matter how many people enter. */
let VIEWS = [{ kind: 'standings', page: 0 }, { kind: 'teams' }];
let viewIndex = 0;
let paused = !!PINNED;
let rotateTimer = null;
let lastTotals = new Map();
let pageSize = 12;

/* Must match the compact-layout media query in style.css. */
const isNarrow = () =>
  window.matchMedia('(max-aspect-ratio: 5/4), (max-height: 620px)').matches;

/* Teams are named the way Little League and ESPN name them on the broadcast -
   Ohio, not Great Lakes - because that is what the room is watching. The region
   seat a pick actually attaches to stays as the secondary label. Both arrive in
   data.json; these tables are only the fallback for a snapshot generated before
   display names existed. */
const ABBR = {
  'Great Lakes': 'OH', 'Metro': 'NJ', 'Mid-Atlantic': 'PA', 'Midwest': 'IA',
  'Mountain': 'NV', 'New England': 'MA', 'Northwest': 'WA', 'Southeast': 'AL',
  'Southwest': 'TX', 'West': 'CA', 'Asia-Pacific': 'KOR', 'Australia': 'AUS',
  'Canada': 'CAN', 'Caribbean': 'DOM', 'Curacao': 'CUW', 'Europe-Africa': 'CZE',
  'Japan': 'JPN', 'Latin America': 'NIC', 'Mexico': 'MEX', 'Panama': 'PAN'
};
const DISPLAY = {
  'Great Lakes': 'Ohio', 'Metro': 'New Jersey', 'Mid-Atlantic': 'Pennsylvania',
  'Midwest': 'Iowa', 'Mountain': 'Nevada', 'New England': 'Massachusetts',
  'Northwest': 'Washington', 'Southeast': 'Alabama', 'Southwest': 'Texas',
  'West': 'California', 'Asia-Pacific': 'South Korea',
  'Caribbean': 'Dominican Republic', 'Europe-Africa': 'Czech Republic',
  'Latin America': 'Nicaragua'
};
const abbr = t => ABBR[t] || String(t).slice(0, 3).toUpperCase();
const shown = t => DISPLAY[t] || t;

const $ = sel => document.querySelector(sel);
const el = (tag, cls, text) => {
  const n = document.createElement(tag);
  if (cls) n.className = cls;
  if (text !== undefined) n.textContent = text;
  return n;
};

/* ---------------------------------------------------------------- fetch */
async function load() {
  // The standalone preview (site/build_preview.py) embeds a snapshot instead
  // of serving data.json, so it can be opened or shared as a single file.
  if (window.__LLWS_DATA__) { render(window.__LLWS_DATA__); return; }
  try {
    const res = await fetch('data.json?t=' + Date.now(), { cache: 'no-store' });
    if (!res.ok) throw new Error(res.status);
    const data = await res.json();
    render(data);
  } catch (err) {
    $('#tick-latest').innerHTML =
      '<span class="dim">Waiting for the next update&hellip;</span>';
  }
}

/* ------------------------------------------------------------- rendering */
function render(data) {
  if (reloadIfStale(data)) return;
  currentData = data;
  renderHeader(data);
  rebuildViews(data);
  renderStandings(data);
  renderTeams(data);
  renderTicker(data);
  fitStandings(data);
  renderDebug(data);
}

/* Rebuild the view list around the current pageSize, keeping the screen the
   operator is looking at. */
function repaginate(data) {
  const pages = Math.max(1, Math.ceil(data.standings.length / pageSize));
  const current = VIEWS[viewIndex];
  VIEWS = [];
  for (let p = 0; p < pages; p++) VIEWS.push({ kind: 'standings', page: p });
  VIEWS.push({ kind: 'teams' });
  viewIndex = Math.min(viewIndex, VIEWS.length - 1);
  if (current && current.kind === 'teams') viewIndex = VIEWS.length - 1;
  showView(viewIndex);
  renderStandings(data);
}

/* Nothing may hide behind the ticker on a TV.

   This measures what the browser actually did rather than trusting the
   estimate, because an unfamiliar player can lay out differently: it reads
   the real distance between two rows and works out how many genuinely fit.
   The old version stepped down one row at a time and gave up after four,
   which on a screen that needed six steps left rows stranded off the bottom
   with no way to reach them. */
function fitStandings(data, guard = 0) {
  if (isNarrow() || guard > 12) return;
  const rows = [].slice.call(document.querySelectorAll('#standings .row'));
  if (rows.length < 2) return;
  const limit = $('#ticker').getBoundingClientRect().top;
  const first = rows[0].getBoundingClientRect();
  const last = rows[rows.length - 1].getBoundingClientRect();
  if (last.bottom <= limit + 1) return;

  const pitch = rows[1].getBoundingClientRect().top - first.top;
  const canFit = pitch > 0
    ? Math.max(1, Math.floor((limit - first.top) / pitch))
    : pageSize - 1;
  const next = Math.max(1, Math.min(canFit, pageSize - 1));
  if (next === pageSize) return;
  pageSize = next;
  repaginate(data);
  fitStandings(data, guard + 1);
}

/* How many rows fit above the ticker at this viewport, and what pages follow. */
function rowsThatFit(n) {
  const avail = $('#ticker').getBoundingClientRect().top
                - $('#standings').getBoundingClientRect().top - 4;
  const vh = window.innerHeight / 100;
  // Nominal row height from CSS, never a measured one: rows stretch to fill
  // the column, so measuring them here would feed their own stretch back into
  // the count and oscillate.
  const declared = getComputedStyle(document.documentElement)
                     .getPropertyValue('--row-h').trim();
  const preferredH = ((parseFloat(declared) || 7.5) + 0.62) * vh;
  // .row min-height + margin: the most that can be crammed in before rows
  // start disappearing behind the ticker.
  const floorH = (5.6 + 0.62) * vh;
  const hardMax = Math.max(1, Math.floor(avail / floorH));
  const preferred = Math.max(1, Math.floor(avail / preferredH));
  return Math.max(1, Math.min(preferred, hardMax, Math.max(n, 1)));
}

function rebuildViews(data) {
  const n = data.standings.length;
  if (isNarrow()) {
    pageSize = n || 1;
  } else {
    pageSize = ROWS_OVERRIDE || rowsThatFit(n);
  }
  const pages = Math.max(1, Math.ceil((n || 1) / pageSize));
  const next = [];
  for (let p = 0; p < pages; p++) next.push({ kind: 'standings', page: p });
  next.push({ kind: 'teams' });

  const current = VIEWS[viewIndex];
  VIEWS = next;
  if (PINNED === 'teams') viewIndex = VIEWS.length - 1;
  else if (PINNED === 'standings') viewIndex = 0;
  else if (!seeded) {
    // First paint after a load: carry on from wherever the last load stopped.
    viewIndex = ((resumeFrom % VIEWS.length) + VIEWS.length) % VIEWS.length;
    seeded = true;
  } else {
    const same = VIEWS.findIndex(v => current && v.kind === current.kind &&
                                      v.page === current.page);
    viewIndex = same >= 0 ? same : 0;
  }
  showView(viewIndex);
  restartRotation();
}

function renderHeader(data) {
  const phase = $('#phase');
  phase.classList.toggle('champ', !!data.champion);
  if (data.champion) {
    phase.textContent =
      (data.champion_display || shown(data.champion)) + ' — World Champion';
  } else if (data.us_champion || data.intl_champion) {
    phase.textContent = 'Championship Sunday';
  } else if (data.games_played === 0) {
    phase.textContent = 'First pitch Aug 19';
  } else {
    const next = data.upcoming.find(g => g.ready) || data.upcoming[0];
    phase.textContent = next ? next.label : 'In progress';
  }
  $('#progress').textContent =
    `Game ${data.games_played} of ${data.games_total}`;
  /* "Updated" reads as "we last looked", so it has to mean that. The
     updater republishes at least every half hour even when nothing has
     happened, so a stale time here is a real fault rather than a quiet
     afternoon. */
  $('#updated').textContent = 'Checked ' + (data.generated_display || '');
}

function pickClass(p) {
  if (p.state === 'world_champion' || p.state === 'side_champion') return 'crown';
  if (!p.alive) return 'out';
  return p.state === 'elimination' ? 'elimination' : 'winners';
}

function renderStandings(data) {
  const list = $('#standings');
  const view = VIEWS[viewIndex] || { kind: 'standings', page: 0 };
  const page = view.kind === 'standings' ? view.page : 0;
  const rows = data.standings.slice(page * pageSize, (page + 1) * pageSize);

  const pages = VIEWS.filter(v => v.kind === 'standings').length;
  $('#page-note').textContent =
    pages > 1 ? `Standings ${page + 1} of ${pages}` : '';

  if (!data.standings.length) {
    list.innerHTML = '';
    const empty = el('li', 'row');
    empty.append(el('div', 'name', 'Entries load after the Aug 18 deadline'));
    list.append(empty);
    return;
  }

  /* FLIP: measure current positions so reordering animates. */
  const before = new Map();
  list.querySelectorAll('.row').forEach(r =>
    before.set(r.dataset.name, r.getBoundingClientRect().top));

  list.innerHTML = '';
  rows.forEach(r => {
    const row = el('li', 'row');
    row.dataset.name = r.name;
    if (r.rank <= 3) row.classList.add('top' + r.rank);

    const rankCell = el('div', 'rank-cell');
    rankCell.append(el('span', 'rank-num', r.rank));
    let mv = '–', mvClass = 'flat';
    if (r.movement > 0) { mv = '▲' + r.movement; mvClass = 'up'; }
    else if (r.movement < 0) { mv = '▼' + Math.abs(r.movement); mvClass = 'down'; }
    rankCell.append(el('span', 'move ' + mvClass, mv));
    row.append(rankCell);

    row.append(el('div', 'name', r.name));

    const picks = el('div', 'picks');
    r.picks.forEach(p => {
      const chip = el('div', 'pick ' + pickClass(p) + (p.rank === 1 ? ' r1' : ''));
      chip.title = `#${p.rank} ${p.display || shown(p.team)} (${p.team}) — ` +
                   `${p.points} pts × rank weight = ${p.contribution}`;
      chip.append(el('span', 'abbr', p.abbr || abbr(p.team)));
      picks.append(chip);
    });
    row.append(picks);

    const alive = el('div', 'alive');
    alive.append(document.createTextNode(r.alive));
    alive.append(el('span', 'of', '/8'));
    row.append(alive);

    const score = el('div', 'score');
    row.append(score);
    countUp(score, lastTotals.has(r.name) ? lastTotals.get(r.name) : r.total,
            r.total);
    if (lastTotals.has(r.name) && lastTotals.get(r.name) !== r.total) {
      row.classList.add('bump');
    }

    list.append(row);
  });

  /* FLIP: play the difference. */
  list.querySelectorAll('.row').forEach(row => {
    const old = before.get(row.dataset.name);
    if (old === undefined) return;
    const delta = old - row.getBoundingClientRect().top;
    if (!delta) return;
    row.style.transform = `translateY(${delta}px)`;
    row.style.transition = 'none';
    requestAnimationFrame(() => {
      row.style.transition = '';
      row.style.transform = '';
    });
  });

  data.standings.forEach(r => lastTotals.set(r.name, r.total));
}

function countUp(node, from, to) {
  if (from === to) { node.textContent = to; return; }
  const start = performance.now(), dur = 900;
  const step = now => {
    const t = Math.min(1, (now - start) / dur);
    const eased = 1 - Math.pow(1 - t, 3);
    node.textContent = Math.round(from + (to - from) * eased);
    if (t < 1) requestAnimationFrame(step);
  };
  requestAnimationFrame(step);
}

function renderTeams(data) {
  const us = $('#teams-us'), intl = $('#teams-intl');
  us.innerHTML = ''; intl.innerHTML = '';
  const order = { world_champion: 0, side_champion: 1, winners: 2, elimination: 3, eliminated: 4 };
  [...data.teams]
    .sort((a, b) => (order[a.state] - order[b.state]) || (b.points - a.points) ||
                    a.team.localeCompare(b.team))
    .forEach(t => {
      const card = el('div', 'team ' + t.state);
      card.append(el('div', 'team-name', t.display || shown(t.team)));
      card.append(el('div', 'team-pts', t.points));
      card.append(el('div', 'team-region', t.team));
      card.append(el('div', 'team-status', t.label));
      const picked = el('div', 'team-picked');
      if (t.picked_by) {
        picked.innerHTML = `picked by <b>${t.picked_by}</b>` +
          (t.picked_at_one ? ` · <b>${t.picked_at_one}</b> at #1` : '');
      } else {
        picked.innerHTML = '<span>picked by nobody</span>';
      }
      card.append(picked);
      (t.side === 'US' ? us : intl).append(card);
    });
}

/* What this particular screen reports about itself. The office TV is a
   BrightSign and behaves differently from any browser here, so rather than
   guess, ?debug=1 puts the numbers on the screen to be read off. */
function renderDebug(data) {
  if (!DEBUG) return;
  let box = $('#debug-box');
  if (!box) {
    box = el('div');
    box.id = 'debug-box';
    document.body.appendChild(box);
  }
  const rows = document.querySelectorAll('#standings .row');
  const pitch = rows.length > 1
    ? Math.round(rows[1].getBoundingClientRect().top -
                 rows[0].getBoundingClientRect().top)
    : 0;
  const supports = (prop, val) => {
    try { return window.CSS && CSS.supports && CSS.supports(prop, val); }
    catch (e) { return 'n/a'; }
  };
  const avail = Math.round($('#ticker').getBoundingClientRect().top
                           - $('#standings').getBoundingClientRect().top);
  box.innerHTML = [
    'viewport ' + window.innerWidth + ' x ' + window.innerHeight +
      '  dpr ' + (window.devicePixelRatio || 1),
    'entries ' + data.standings.length + '   rows/page ' + pageSize +
      '   rendered ' + rows.length + '   views ' + VIEWS.length +
      '   showing ' + (viewIndex + 1),
    'space above ticker ' + avail + 'px   row pitch ' + pitch + 'px',
    'resumed at view ' + resumeFrom + '   rotating every ' +
      Math.round(rotateMs() / 1000) + 's' + (paused ? ' (paused)' : ''),
    'flex gap ' + supports('row-gap', '1px') +
      '   clip-path ' + supports('clip-path', 'polygon(0 0, 1px 0, 0 1px)') +
      '   css vars ' + supports('--x', '1px'),
    navigator.userAgent
  ].join('<br>');
}

function renderTicker(data) {
  const latest = data.recent[0];
  $('#tick-latest').innerHTML = latest
    ? `<span class="win">${latest.winner_display || shown(latest.winner)}</span>` +
      ` def. ${latest.loser_display || shown(latest.loser)}` +
      ` <span class="dim">&mdash; ${latest.label} (G${latest.game})</span>`
    : '<span class="dim">No games played yet</span>';

  const next = data.upcoming[0];
  $('#tick-next').innerHTML = next
    ? `${next.a_display || shown(next.a)} <span class="dim">vs</span> ` +
      `${next.b_display || shown(next.b)}` +
      ` <span class="dim">&mdash; ${next.label}, ` +
      `${fmtWhen(next.date, next.time, data.timezone || 'PT')}</span>`
    : '<span class="dim">Tournament complete</span>';
}

function fmtDate(iso) {
  const d = new Date(iso + 'T12:00:00');
  return d.toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' });
}

/* Today needs no date on it, and the space buys the full matchup. */
function fmtWhen(iso, time, tz) {
  const today = new Date();
  const pad = n => String(n).padStart(2, '0');
  const key = `${today.getFullYear()}-${pad(today.getMonth() + 1)}-${pad(today.getDate())}`;
  return (iso === key ? '' : fmtDate(iso) + ' ') + time + ' ' + tz;
}

/* ------------------------------------------------------------- rotation */
function showView(i) {
  viewIndex = (i + VIEWS.length) % VIEWS.length;
  if (!PINNED) {
    try { localStorage.setItem(VIEW_KEY, viewIndex); } catch (e) {}
  }
  const view = VIEWS[viewIndex];
  if (isNarrow()) {
    // On a phone nothing rotates: both sections stack and the page scrolls,
    // so a screen never changes out from under whoever is reading it.
    $('#view-standings').classList.remove('hidden');
    $('#view-teams').classList.remove('hidden');
    $('#view-dots').innerHTML = '';
    return;
  }
  $('#view-standings').classList.toggle('hidden', view.kind !== 'standings');
  $('#view-teams').classList.toggle('hidden', view.kind !== 'teams');
  const dots = $('#view-dots');
  dots.innerHTML = '';
  VIEWS.forEach((_, idx) =>
    dots.append(el('span', 'vdot' + (idx === viewIndex ? ' on' : ''))));
}

/* Paging between standings pages re-renders that page's rows. */
function goto(i) {
  showView(i);
  if (currentData) {
    renderStandings(currentData);
  }
}
let currentData = null;

function restartRotation() {
  clearInterval(rotateTimer);
  if (paused || isNarrow() || VIEWS.length < 2) return;
  rotateTimer = setInterval(() => goto(viewIndex + 1), rotateMs());
}

document.addEventListener('keydown', e => {
  if (e.code === 'Space') {
    e.preventDefault();
    paused = !paused;
    restartRotation();
  } else if (e.code === 'ArrowRight') {
    goto(viewIndex + 1); restartRotation();
  } else if (e.code === 'ArrowLeft') {
    goto(viewIndex - 1); restartRotation();
  } else if (e.key === '[') {
    nudgeSafe(0.5);           // crop more: pull the picture in
  } else if (e.key === ']') {
    nudgeSafe(-0.5);          // crop less: push the picture out
  } else if (e.key === '0') {
    safePercent = 3; nudgeSafe(0);
  }
});

applySafe(false);

/* Re-measure on resize: row capacity per page depends on viewport height. */
let resizeTimer;
window.addEventListener('resize', () => {
  clearTimeout(resizeTimer);
  resizeTimer = setTimeout(() => { if (currentData) render(currentData); }, 200);
});

showView(viewIndex);
restartRotation();
load();
if (!window.__LLWS_DATA__) setInterval(load, REFRESH_MS);
