/* LLWS 2026 Office Pool leaderboard.
   Reads data.json (regenerated by pool/update.py). No dependencies, no build.

   URL options:  ?view=standings|teams   pin a single view
                 ?rotate=20              seconds per view (default 14)
   Keyboard:     Space pauses rotation, Left/Right switch views. */

const params = new URLSearchParams(location.search);
const ROTATE_OVERRIDE = parseFloat(params.get('rotate'));
const REFRESH_MS = 60000;
const PINNED = params.get('view');

/* Dwell per view: big pools paginate into more views, so shorten each one to
   keep a full cycle around a minute rather than a minute and a half. */
function rotateMs() {
  if (ROTATE_OVERRIDE) return ROTATE_OVERRIDE * 1000;
  const per = Math.min(14, Math.max(8, 75 / Math.max(1, VIEWS.length)));
  return per * 1000;
}

/* Views are built at render time: the standings paginate so rows stay large
   enough to read across a room no matter how many people enter. */
let VIEWS = [{ kind: 'standings', page: 0 }, { kind: 'teams' }];
let viewIndex = 0;
let paused = !!PINNED;
let rotateTimer = null;
let lastTotals = new Map();
let pageSize = 12;

/* Must match the compact-layout media query in style.css. */
const isNarrow = () =>
  window.matchMedia('(max-aspect-ratio: 5/4), (max-height: 620px)').matches;

/* Teams are named the way Little League and ESPN name them on the broadcast -
   Ohio, not Great Lakes - because that is what the room is watching. The region
   seat a pick actually attaches to stays as the secondary label. Both arrive in
   data.json; these tables are only the fallback for a snapshot generated before
   display names existed. */
const ABBR = {
  'Great Lakes': 'OH', 'Metro': 'NJ', 'Mid-Atlantic': 'PA', 'Midwest': 'IA',
  'Mountain': 'NV', 'New England': 'MA', 'Northwest': 'WA', 'Southeast': 'AL',
  'Southwest': 'TX', 'West': 'CA', 'Asia-Pacific': 'KOR', 'Australia': 'AUS',
  'Canada': 'CAN', 'Caribbean': 'DOM', 'Curacao': 'CUW', 'Europe-Africa': 'CZE',
  'Japan': 'JPN', 'Latin America': 'NIC', 'Mexico': 'MEX', 'Panama': 'PAN'
};
const DISPLAY = {
  'Great Lakes': 'Ohio', 'Metro': 'New Jersey', 'Mid-Atlantic': 'Pennsylvania',
  'Midwest': 'Iowa', 'Mountain': 'Nevada', 'New England': 'Massachusetts',
  'Northwest': 'Washington', 'Southeast': 'Alabama', 'Southwest': 'Texas',
  'West': 'California', 'Asia-Pacific': 'South Korea',
  'Caribbean': 'Dominican Republic', 'Europe-Africa': 'Czech Republic',
  'Latin America': 'Nicaragua'
};
const abbr = t => ABBR[t] || String(t).slice(0, 3).toUpperCase();
const shown = t => DISPLAY[t] || t;

const $ = sel => document.querySelector(sel);
const el = (tag, cls, text) => {
  const n = document.createElement(tag);
  if (cls) n.className = cls;
  if (text !== undefined) n.textContent = text;
  return n;
};

/* ---------------------------------------------------------------- fetch */
async function load() {
  // The standalone preview (site/build_preview.py) embeds a snapshot instead
  // of serving data.json, so it can be opened or shared as a single file.
  if (window.__LLWS_DATA__) { render(window.__LLWS_DATA__); return; }
  try {
    const res = await fetch('data.json?t=' + Date.now(), { cache: 'no-store' });
    if (!res.ok) throw new Error(res.status);
    const data = await res.json();
    render(data);
  } catch (err) {
    $('#tick-latest').innerHTML =
      '<span class="dim">Waiting for the next update&hellip;</span>';
  }
}

/* ------------------------------------------------------------- rendering */
function render(data) {
  currentData = data;
  renderHeader(data);
  rebuildViews(data);
  renderStandings(data);
  renderTeams(data);
  renderTicker(data);
  fitStandings(data);
}

/* Nothing may hide behind the ticker on a TV: shrink the page until it fits. */
function fitStandings(data, guard = 0) {
  if (isNarrow() || guard > 4) return;
  const rows = [...document.querySelectorAll('#standings .row')];
  if (rows.length < 2) return;
  const bottom = rows[rows.length - 1].getBoundingClientRect().bottom;
  const limit = $('#ticker').getBoundingClientRect().top;
  if (bottom <= limit) return;
  pageSize = Math.max(4, pageSize - 1);
  const pages = Math.max(1, Math.ceil(data.standings.length / pageSize));
  const current = VIEWS[viewIndex];
  VIEWS = [];
  for (let p = 0; p < pages; p++) VIEWS.push({ kind: 'standings', page: p });
  VIEWS.push({ kind: 'teams' });
  viewIndex = Math.min(viewIndex, VIEWS.length - 1);
  if (current?.kind === 'teams') viewIndex = VIEWS.length - 1;
  showView(viewIndex);
  renderStandings(data);
  fitStandings(data, guard + 1);
}

/* How many rows fit above the ticker at this viewport, and what pages follow. */
function rebuildViews(data) {
  const n = data.standings.length;
  if (isNarrow()) {
    pageSize = n || 1;
  } else {
    // Row height comes from CSS (--row-h + margin); measure a real row when
    // one exists, and fall back to the declared value on first paint.
    const sample = document.querySelector('#standings .row');
    let rowH = window.innerHeight * 0.081;
    if (sample) {
      const box = sample.getBoundingClientRect();
      rowH = box.height + parseFloat(getComputedStyle(sample).marginTop || 0);
    }
    const avail = $('#ticker').getBoundingClientRect().top
                  - $('#standings').getBoundingClientRect().top - 4;
    pageSize = Math.max(6, Math.floor(avail / rowH));
  }
  const pages = Math.max(1, Math.ceil((n || 1) / pageSize));
  const next = [];
  for (let p = 0; p < pages; p++) next.push({ kind: 'standings', page: p });
  next.push({ kind: 'teams' });

  const current = VIEWS[viewIndex];
  VIEWS = next;
  if (PINNED === 'teams') viewIndex = VIEWS.length - 1;
  else if (PINNED === 'standings') viewIndex = 0;
  else {
    const same = VIEWS.findIndex(v => v.kind === current?.kind &&
                                      v.page === current?.page);
    viewIndex = same >= 0 ? same : 0;
  }
  showView(viewIndex);
  restartRotation();
}

function renderHeader(data) {
  const phase = $('#phase');
  phase.classList.toggle('champ', !!data.champion);
  if (data.champion) {
    phase.textContent =
      (data.champion_display || shown(data.champion)) + ' — World Champion';
  } else if (data.us_champion || data.intl_champion) {
    phase.textContent = 'Championship Sunday';
  } else if (data.games_played === 0) {
    phase.textContent = 'First pitch Aug 19';
  } else {
    const next = data.upcoming.find(g => g.ready) || data.upcoming[0];
    phase.textContent = next ? next.label : 'In progress';
  }
  $('#progress').textContent =
    `Game ${data.games_played} of ${data.games_total}`;
  $('#updated').textContent = 'Updated ' + (data.generated_display || '');
}

function pickClass(p) {
  if (p.state === 'world_champion' || p.state === 'side_champion') return 'crown';
  if (!p.alive) return 'out';
  return p.state === 'elimination' ? 'elimination' : 'winners';
}

function renderStandings(data) {
  const list = $('#standings');
  const view = VIEWS[viewIndex] || { kind: 'standings', page: 0 };
  const page = view.kind === 'standings' ? view.page : 0;
  const rows = data.standings.slice(page * pageSize, (page + 1) * pageSize);

  const pages = VIEWS.filter(v => v.kind === 'standings').length;
  $('#page-note').textContent =
    pages > 1 ? `Standings ${page + 1} of ${pages}` : '';

  if (!data.standings.length) {
    list.innerHTML = '';
    const empty = el('li', 'row');
    empty.append(el('div', 'name', 'Entries load after the Aug 18 deadline'));
    list.append(empty);
    return;
  }

  /* FLIP: measure current positions so reordering animates. */
  const before = new Map();
  list.querySelectorAll('.row').forEach(r =>
    before.set(r.dataset.name, r.getBoundingClientRect().top));

  list.innerHTML = '';
  rows.forEach(r => {
    const row = el('li', 'row');
    row.dataset.name = r.name;
    if (r.rank <= 3) row.classList.add('top' + r.rank);

    const rankCell = el('div', 'rank-cell');
    rankCell.append(el('span', 'rank-num', r.rank));
    let mv = '–', mvClass = 'flat';
    if (r.movement > 0) { mv = '▲' + r.movement; mvClass = 'up'; }
    else if (r.movement < 0) { mv = '▼' + Math.abs(r.movement); mvClass = 'down'; }
    rankCell.append(el('span', 'move ' + mvClass, mv));
    row.append(rankCell);

    row.append(el('div', 'name', r.name));

    const picks = el('div', 'picks');
    r.picks.forEach(p => {
      const chip = el('div', 'pick ' + pickClass(p) + (p.rank === 1 ? ' r1' : ''));
      chip.title = `#${p.rank} ${p.display || shown(p.team)} (${p.team}) — ` +
                   `${p.points} pts × rank weight = ${p.contribution}`;
      chip.append(el('span', 'abbr', p.abbr || abbr(p.team)));
      picks.append(chip);
    });
    row.append(picks);

    const alive = el('div', 'alive');
    alive.append(document.createTextNode(r.alive));
    alive.append(el('span', 'of', '/8'));
    row.append(alive);

    const score = el('div', 'score');
    row.append(score);
    countUp(score, lastTotals.get(r.name) ?? r.total, r.total);
    if (lastTotals.has(r.name) && lastTotals.get(r.name) !== r.total) {
      row.classList.add('bump');
    }

    list.append(row);
  });

  /* FLIP: play the difference. */
  list.querySelectorAll('.row').forEach(row => {
    const old = before.get(row.dataset.name);
    if (old === undefined) return;
    const delta = old - row.getBoundingClientRect().top;
    if (!delta) return;
    row.style.transform = `translateY(${delta}px)`;
    row.style.transition = 'none';
    requestAnimationFrame(() => {
      row.style.transition = '';
      row.style.transform = '';
    });
  });

  data.standings.forEach(r => lastTotals.set(r.name, r.total));
}

function countUp(node, from, to) {
  if (from === to) { node.textContent = to; return; }
  const start = performance.now(), dur = 900;
  const step = now => {
    const t = Math.min(1, (now - start) / dur);
    const eased = 1 - Math.pow(1 - t, 3);
    node.textContent = Math.round(from + (to - from) * eased);
    if (t < 1) requestAnimationFrame(step);
  };
  requestAnimationFrame(step);
}

function renderTeams(data) {
  const us = $('#teams-us'), intl = $('#teams-intl');
  us.innerHTML = ''; intl.innerHTML = '';
  const order = { world_champion: 0, side_champion: 1, winners: 2, elimination: 3, eliminated: 4 };
  [...data.teams]
    .sort((a, b) => (order[a.state] - order[b.state]) || (b.points - a.points) ||
                    a.team.localeCompare(b.team))
    .forEach(t => {
      const card = el('div', 'team ' + t.state);
      card.append(el('div', 'team-name', t.display || shown(t.team)));
      card.append(el('div', 'team-pts', t.points));
      card.append(el('div', 'team-region', t.team));
      card.append(el('div', 'team-status', t.label));
      const picked = el('div', 'team-picked');
      if (t.picked_by) {
        picked.innerHTML = `picked by <b>${t.picked_by}</b>` +
          (t.picked_at_one ? ` · <b>${t.picked_at_one}</b> at #1` : '');
      } else {
        picked.innerHTML = '<span>picked by nobody</span>';
      }
      card.append(picked);
      (t.side === 'US' ? us : intl).append(card);
    });
}

function renderTicker(data) {
  const latest = data.recent[0];
  $('#tick-latest').innerHTML = latest
    ? `<span class="win">${latest.winner_display || shown(latest.winner)}</span>` +
      ` def. ${latest.loser_display || shown(latest.loser)}` +
      ` <span class="dim">&mdash; ${latest.label} (G${latest.game})</span>`
    : '<span class="dim">No games played yet</span>';

  const next = data.upcoming[0];
  $('#tick-next').innerHTML = next
    ? `${next.a_display || shown(next.a)} <span class="dim">vs</span> ` +
      `${next.b_display || shown(next.b)}` +
      ` <span class="dim">&mdash; ${next.label}, ${fmtDate(next.date)}` +
      ` ${next.time} ${data.timezone || 'PT'}</span>`
    : '<span class="dim">Tournament complete</span>';
}

function fmtDate(iso) {
  const d = new Date(iso + 'T12:00:00');
  return d.toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' });
}

/* ------------------------------------------------------------- rotation */
function showView(i) {
  viewIndex = (i + VIEWS.length) % VIEWS.length;
  const view = VIEWS[viewIndex];
  if (isNarrow()) {
    // On a phone nothing rotates: both sections stack and the page scrolls,
    // so a screen never changes out from under whoever is reading it.
    $('#view-standings').classList.remove('hidden');
    $('#view-teams').classList.remove('hidden');
    $('#view-dots').innerHTML = '';
    return;
  }
  $('#view-standings').classList.toggle('hidden', view.kind !== 'standings');
  $('#view-teams').classList.toggle('hidden', view.kind !== 'teams');
  const dots = $('#view-dots');
  dots.innerHTML = '';
  VIEWS.forEach((_, idx) =>
    dots.append(el('span', 'vdot' + (idx === viewIndex ? ' on' : ''))));
}

/* Paging between standings pages re-renders that page's rows. */
function goto(i) {
  showView(i);
  if (currentData) {
    renderStandings(currentData);
  }
}
let currentData = null;

function restartRotation() {
  clearInterval(rotateTimer);
  if (paused || isNarrow() || VIEWS.length < 2) return;
  rotateTimer = setInterval(() => goto(viewIndex + 1), rotateMs());
}

document.addEventListener('keydown', e => {
  if (e.code === 'Space') {
    e.preventDefault();
    paused = !paused;
    restartRotation();
  } else if (e.code === 'ArrowRight') {
    goto(viewIndex + 1); restartRotation();
  } else if (e.code === 'ArrowLeft') {
    goto(viewIndex - 1); restartRotation();
  }
});

/* Re-measure on resize: row capacity per page depends on viewport height. */
let resizeTimer;
window.addEventListener('resize', () => {
  clearTimeout(resizeTimer);
  resizeTimer = setTimeout(() => { if (currentData) render(currentData); }, 200);
});

showView(viewIndex);
restartRotation();
load();
if (!window.__LLWS_DATA__) setInterval(load, REFRESH_MS);
